apiVersion: v1
kind: Service
metadata:
  name: hello-app-cloud-spanner
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-app-cloud-spanner
