name: batch-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/batch-ci.yml'
      - 'batch/**'
  pull_request:
    paths:
      - '.github/workflows/batch-ci.yml'
      - 'batch/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build aiml-workloads container
        run: |
          cd batch/aiml-workloads/src
          docker build --tag aiml-workloads .
