name: pubsub-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pubsub-ci.yml'
      - 'cloud-pubsub/**'
  pull_request:
    paths:
      - '.github/workflows/pubsub-ci.yml'
      - 'cloud-pubsub/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build cloud-pubsub container
        run: |
          cd cloud-pubsub
          docker build --tag cloud-pubsub .
