name: quickstart-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/quickstart-ci.yml'
      - 'quickstart/**'
  pull_request:
    paths:
      - '.github/workflows/quickstart-ci.yml'
      - 'quickstart/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build quickstart/dotnet container
        run: |
          cd quickstart/dotnet
          docker build --tag quickstart-dotnet .
      - name: build quickstart-go container
        run: |
          cd quickstart/go
          docker build --tag quickstart-go .
      - name: build quickstart-java container
        run: |
          cd quickstart/java
          docker build --tag quickstart-java .
      - name: build quickstart-nodejs container
        run: |
          cd quickstart/nodejs
          docker build --tag quickstart-nodejs .
      - name: build quickstart-php container
        run: |
          cd quickstart/php
          docker build --tag quickstart-php .
      - name: build quickstart-python container
        run: |
          cd quickstart/python
          docker build --tag quickstart-python .
      - name: build quickstart-ruby container
        run: |
          cd quickstart/ruby
          docker build --tag quickstart-ruby .
