name: workload-metrics-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workload-metrics-ci.yml'
      - 'workload-metrics/**'
  pull_request:
    paths:
      - '.github/workflows/workload-metrics-ci.yml'
      - 'workload-metrics/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build workload-metrics container
        run: |
          cd workload-metrics
          docker build --tag workload-metrics .
